USE spring_blog_db;

insert into posts (title, body) values ('Coke''s hartebeest', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into posts (title, body) values ('Pie, indian tree', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into posts (title, body) values ('Emu', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into posts (title, body) values ('Bison, american', 'In congue. Etiam justo. Etiam pretium iaculis justo.');
insert into posts (title, body) values ('Toucan, red-billed', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.');
insert into posts (title, body) values ('Sun gazer', 'Fusce consequat. Nulla nisl. Nunc nisl.');
insert into posts (title, body) values ('Ground legaan', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.');
insert into posts (title, body) values ('Corella, long-billed', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.');
insert into posts (title, body) values ('Gecko (unidentified)', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into posts (title, body) values ('White-browed owl', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into posts (title, body) values ('Macaw, blue and gold', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into posts (title, body) values ('Pied avocet', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.');
insert into posts (title, body) values ('Marabou stork', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into posts (title, body) values ('Fringe-eared oryx', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into posts (title, body) values ('Polar bear', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into posts (title, body) values ('African lynx', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into posts (title, body) values ('Tortoise, desert', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into posts (title, body) values ('Red brocket', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into posts (title, body) values ('Roseate cockatoo', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into posts (title, body) values ('Helmeted guinea fowl', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into posts (title, body) values ('Brazilian tapir', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into posts (title, body) values ('Godwit, hudsonian', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into posts (title, body) values ('Sparrow, rufous-collared', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.');
insert into posts (title, body) values ('Moorhen, purple', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.');
insert into posts (title, body) values ('Dragon, netted rock', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.');
insert into posts (title, body) values ('Blue waxbill', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into posts (title, body) values ('Iguana, marine', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into posts (title, body) values ('Nuthatch, red-breasted', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into posts (title, body) values ('Seal, harbor', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into posts (title, body) values ('Greater blue-eared starling', 'Fusce consequat. Nulla nisl. Nunc nisl.');
insert into posts (title, body) values ('Ring-necked pheasant', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into posts (title, body) values ('Trumpeter, dark-winged', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into posts (title, body) values ('Elephant, african', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.');
insert into posts (title, body) values ('Caracal', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.');
insert into posts (title, body) values ('Toddy cat', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into posts (title, body) values ('White-winged tern', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.');
insert into posts (title, body) values ('Red-billed toucan', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into posts (title, body) values ('Swallow (unidentified)', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into posts (title, body) values ('Blue and yellow macaw', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into posts (title, body) values ('Black-backed magpie', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.');
insert into posts (title, body) values ('Madagascar hawk owl', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into posts (title, body) values ('Koala', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into posts (title, body) values ('Tropical buckeye butterfly', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into posts (title, body) values ('Colobus, white-mantled', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into posts (title, body) values ('King vulture', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into posts (title, body) values ('Lizard, collared', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.');
insert into posts (title, body) values ('American crow', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.');
insert into posts (title, body) values ('Cereopsis goose', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.');
insert into posts (title, body) values ('Yellow mongoose', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into posts (title, body) values ('Grouse, sage', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.');